[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]
minimum_release_age_excludes = ["npm:@earendil-works/pi-coding-agent"]

[tools]
ast-grep = "latest"
bat = "latest"
crush = "latest"
difftastic = "latest"
fd = "latest"
"github:can1357/oh-my-pi" = "latest"
glow = "latest"
gum = "latest"
jq = "latest"
node = "lts"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@metabase/cli" = "latest"
"npm:@posthog/cli" = "latest"
"npm:hunkdiff" = "latest"
"npm:sideshow" = "latest"
prek = "latest"
ripgrep = "latest"
shellcheck = "latest"
usage = "latest"
