brew "aspell"
brew "bash"
brew "bat"
brew "coreutils"
brew "direnv"
brew "fasd"
brew "fd"
brew "fzf"
brew "git"
brew "multimarkdown"
brew "ripgrep"
brew "shellcheck"
brew "stow"
brew "tidy-html5"
brew "zsh"
brew "zsh-syntax-highlighting"

tap "d12frosted/emacs-plus"
brew "emacs-plus@27", fetch_HEAD: true
