brew "aspell"
brew "bash"
brew "cmake"
brew "coreutils"
brew "direnv"
brew "duckdb"
brew "fzf"
brew "git"
brew "less"
brew "mise"
brew "multimarkdown"
brew "starship"
brew "stow"
brew "tidy-html5"
brew "tmux"
brew "zsh"
brew "zsh-syntax-highlighting"

cask "1password-cli"
cask "font-source-code-pro"
cask "vivaldi"

tap "d12frosted/emacs-plus"
cask "emacs-plus-app@master"
