onboarding = false

[ui]
prompt_new_tab_name = false
pane_scrollbars = false
show_agent_labels_on_pane_borders = true

agent_panel_sort = "priority"

[ui.sidebar.agents]
rows = [
  ["state_icon", "workspace", { token = "tab", fg = "#D8DEE9", dim = false }],
  [{ token = "agent", dim = false }],
]

[ui.sound]
enabled = true

[ui.toast]
delivery = "herdr"

[keys]
prefix = "ctrl+l"
new_tab = "prefix+n"
rename_tab = "prefix+,"
split_vertical = "prefix+|"
previous_workspace = "ctrl+alt+["
next_workspace = "ctrl+alt+]"
previous_tab = "alt+["
next_tab = "alt+]"
fullscreen = "prefix+z"
focus_pane_left = "shift+left"
focus_pane_down = "shift+down"
focus_pane_up = "shift+up"
focus_pane_right = "shift+right"

[theme]
name = "nord"
auto_switch = false

[theme.custom]
overlay0 = "#646E82"

[experimental]
kitty_graphics = true
